name: On Push

on: [push]

jobs:
  BuildAndTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            libframework: net45
            binframework: netcoreapp2
          - os: ubuntu-latest
            libframework: netstandard2
            binframework: netcoreapp2
    env:
      test-runner: test/ICSharpCode.SharpZipLib.TestBootstrapper/ICSharpCode.SharpZipLib.TestBootstrapper.csproj
      test-report: docs/nunit3-test-results-debug.xml
    steps:
    - uses: actions/checkout@v2
      
    - if: matrix.binframework == 'netcoreapp2'
      name: Setup up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
      
    - name: Build library
      run: dotnet build -c ${{ matrix.configuration }} -f ${{ matrix.libframework }} src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
      
    - name: Build tests
      run: dotnet build -c ${{ matrix.configuration }} -f ${{ matrix.binframework }} test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj

    - name: Run tests
      run: dotnet run -c ${{ matrix.configuration }} -f ${{ matrix.binframework }} -p ${{ env.test-runner }} --result=${{ env.test-report }}

    - name: Upload nuget package artifact
      if: 'false'
      uses: actions/upload-artifact@v1
      with:
        name: Nuget package
        path: src/ICSharpCode.SharpZipLib/SharpZipLib.nupkg

    - name: Upload test report artifact
      uses: actions/upload-artifact@v1
      with:
        name: Test report
        path: ${{ env.test-report }}
